#######################################
# Defective diamond (one vacancy)     #
#######################################

output_dir: 'output/defect'

steps:
- name: scf
  command: pw.x

- name: bands
  command: pw.x

- name: bands_data
  command: bands.x

- name: nscf
  command: pw.x

- name: dos
  command: dos.x

vars:
  potentials_dir: 'potentials'
  prefix: 'DIA'
  output_dir: 'output/defect'
  doping: ''

  conv_thr: '1.0d-8'

  cell_config: |
    ibrav = 1,
    celldm(1) = 6.60,
    nat = 8,
    ntyp = 1

  atomic_species: |
    ATOMIC_SPECIES
    C 12.011 C_PBE_hard.mt

  atomic_positions: |
    ATOMIC_POSITIONS
    C  0.000  0.000  0.000
    C  0.500  0.500  0.000
    C  0.500  0.000  0.500
    C  0.000  0.500  0.500
    C  0.250  0.250  0.250
    C  0.750  0.750  0.250
    C  0.750  0.250  0.750
    C  0.250  0.750  0.750
